provider "google" { project = var.project_id region = var.region }
resource "google_project_service" "run" { service = "run.googleapis.com" disable_on_destroy = false }
resource "google_project_service" "secretmanager" { service = "secretmanager.googleapis.com" disable_on_destroy = false }
resource "google_service_account" "run" { account_id = "${var.service_name}-run" display_name = "CDM Cloud Run" }
locals { secrets = { DATABASE_URL = var.database_url, NEXTAUTH_SECRET = var.nextauth_secret, GOOGLE_CLIENT_ID = var.google_client_id, GOOGLE_CLIENT_SECRET = var.google_client_secret, GEMINI_API_KEY = var.gemini_api_key, ANTHROPIC_API_KEY = var.anthropic_api_key, SKRIBBY_API_KEY = var.skribby_api_key, WEBHOOK_SECRET = var.webhook_secret, SKRIBBY_BASE_URL = "https://platform.skribby.io/api/v1", APP_URL = var.app_url, TEST_CALL_ENABLED = "true" } }
resource "google_secret_manager_secret" "app" { for_each = local.secrets secret_id = "${var.service_name}-${lower(each.key)}" replication { auto {} } depends_on = [google_project_service.secretmanager] }
resource "google_secret_manager_secret_version" "app" { for_each = local.secrets secret = google_secret_manager_secret.app[each.key].id secret_data = each.value }
resource "google_project_iam_member" "secret_access" { for_each = local.secrets project = var.project_id role = "roles/secretmanager.secretAccessor" member = "serviceAccount:${google_service_account.run.email}" }
resource "google_cloud_run_v2_service" "app" { name = var.service_name location = var.region depends_on = [google_project_service.run] template { service_account = google_service_account.run.email containers { image = var.container_image ports { container_port = 3000 } env { name = "NODE_ENV" value = "production" } env { name = "APP_URL" value = var.app_url } env { name = "NEXTAUTH_URL" value = var.app_url } dynamic "env" { for_each = local.secrets content { name = env.key value_source { secret_key_ref { secret = google_secret_manager_secret.app[env.key].secret_id version = "latest" } } } } } } traffic { percent = 100 type = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST" } }
resource "google_cloud_run_v2_service_iam_member" "public" { name = google_cloud_run_v2_service.app.name location = google_cloud_run_v2_service.app.location role = "roles/run.invoker" member = "allUsers" }
